Repository misha-mikhail/messenger, pull requests merged in 2020-04, with the labels that each got.

#29 Fix #4: Аутентификация
  README.md
  docs/configuration-files.md
  packages/server/.gitignore
  packages/server/appSettings.template.json
  packages/server/package-lock.json
  packages/server/package.json
  packages/server/src/auth/JwtPayload.ts
  packages/server/src/auth/index.ts
  packages/server/src/auth/jwt.ts
  packages/server/src/controllers/AuthController.ts
  packages/server/src/controllers/TestController.ts
  packages/server/src/controllers/UsersController.ts
  packages/server/src/database/abstractions/abstract-repository.ts
  packages/server/src/database/entities/User.ts
  packages/server/src/database/repositories/AbstractRepository.ts
  packages/server/src/database/repositories/MessageRepository.ts
  packages/server/src/database/repositories/UserRepository.ts
  packages/server/src/database/repositories/index.ts
  packages/server/src/endpoint-queries/GetUserQuery.ts
  packages/server/src/endpoint-queries/UserCredentials.ts
  packages/server/src/endpoint-queries/get-users-query.ts
  packages/server/src/server.ts
  packages/web/src/index.ts
Labels: architectural, docs, enhancement

#30 Извлёк UserRepository.getUserInfo() из GET /users/get.
  packages/server/src/controllers/UsersController.ts
  packages/server/src/database/repositories/UserRepository.ts
Labels: refac

#35 Fix #10: PATCH /users/edit-bio
  packages/server/src/controllers/UsersController.ts
  packages/server/src/database/repositories/UserRepository.ts
Labels: enhancement

#36 Fix #6: Вынести конфигурацию БД-соединения в конфиг
  README.md
  packages/server/appSettings.template.json
  packages/server/src/app-settings/AppSettingsJson.ts
  packages/server/src/app-settings/functions.ts
  packages/server/src/app-settings/index.ts
  packages/server/src/auth/jwt.ts
  packages/server/src/database/connection.ts
  packages/server/src/extensions/FileExtensions.ts
Labels: enhancement

#38 Fix #33: Создать бойлерплейт для @chat/web
  README.md
  package.json
  packages/server/package-lock.json
  packages/server/package.json
  packages/server/src/index.ts
  packages/server/src/server.ts
  packages/web/.gitignore
  packages/web/README.md
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/public/index.html
  packages/web/public/manifest.json
  packages/web/public/robots.txt
  packages/web/src/App.css
  packages/web/src/App.test.tsx
  packages/web/src/App.tsx
  packages/web/src/Components/Auth/Auth.tsx
  packages/web/src/Components/Auth/LoginForm.tsx
  packages/web/src/Components/Auth/RegisterForm.tsx
  packages/web/src/Components/Home.tsx
  packages/web/src/index.css
  packages/web/src/index.ts
  packages/web/src/index.tsx
  packages/web/src/react-app-env.d.ts
  packages/web/src/serviceWorker.ts
  packages/web/src/setupTests.ts
  packages/web/tsconfig.build.json
  packages/web/tsconfig.json
Labels: backend, docs, frontend

#40 Fix #39: Одновременный запуск веб-приложения и сервера.
  README.md
  package-lock.json
  package.json
Labels: js-gay-config-shit

#45 Resolve #9: Dependency Injection
  packages/server/package.json
  packages/server/src/auth/jwt.ts
  packages/server/src/constants/ContainerKeys.ts
  packages/server/src/constants/index.ts
  packages/server/src/controllers/AuthController.ts
  packages/server/src/controllers/UsersController.ts
  packages/server/src/database/entities/Conversation.ts
  packages/server/src/database/entities/Message.ts
  packages/server/src/database/entities/User.ts
  packages/server/src/database/repositories/MessageRepository.ts
  packages/server/src/database/repositories/UserRepository.ts
  packages/server/src/index.ts
  packages/server/src/server.ts
Labels: architectural, backend

#46 Пофиксил ошибку в корневом README.
  README.md
Labels: docs

#47 GitHub Workflow — build-all job.
  .github/workflows/nodejs.yml
  package.json
  packages/server/package.json
  packages/shared/package.json
  packages/web/package.json
Labels: js-config-shit, refac

#55 Resolve #22: Прикручен логгер, логи пока только в терм
  package.json
  packages/server/.gitignore
  packages/server/package-lock.json
  packages/server/package.json
  packages/server/src/middlewares/LoggingMiddleware.ts
  packages/server/src/server.ts
Labels: @chat/server, enhancement
